# Add and Remove elements from a numpy array

---

- np.append(arr,value)
- np.vstack((arr,value))
- np.hstack((arr,value))


In [8]:
import numpy as np

vector = np.arange(4)
print(vector)

vector = np.append(vector,-50)
print("After appending value- 50 : ",vector,end="\n\n")

matrix = np.arange(10,22).reshape((3,4))
print(matrix)

row = [-2, 34, 17, 9]
col =[[-36],[-44],[14],[31]]

matrix = np.vstack((matrix,row))
print("After inserting a new row :\n",matrix)

matrix = np.hstack((matrix,col))
print("After inserting a column :\n",matrix)



[0 1 2 3]
After appending value- 50 :  [  0   1   2   3 -50]

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
After inserting a new row :
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [-2 34 17  9]]
After inserting a column :
 [[ 10  11  12  13 -36]
 [ 14  15  16  17 -44]
 [ 18  19  20  21  14]
 [ -2  34  17   9  31]]


---
- np.insert(arr,index,value,axis)

In [14]:
import numpy as np

vector = np.arange(5)
print(vector)

vector = np.insert(vector,1,-100)
print("After inserting value -1000 at index 1 : ",vector,end="\n\n")

matrix = np.arange(10).reshape((2,5))
print(matrix)

row = [63, 0, 7, -75, 61]
matrix = np.insert(matrix, 0, row, axis=0)  # axis 0 for row and 1 for column and 2 for depth and so on. 
print("After inserting values at row 0 :\n",matrix)

col = [100, 200, 300]
matrix = np.insert(matrix, 2, col, axis=1)
print("After inserting a column at index 2 :\n",matrix)


[0 1 2 3 4]
After inserting value -1000 at index 1 :  [   0 -100    1    2    3    4]

[[0 1 2 3 4]
 [5 6 7 8 9]]
After inserting values at row 0 :
 [[ 63   0   7 -75  61]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]
After inserting a column at index 2 :
 [[ 63   0 100   7 -75  61]
 [  0   1 200   2   3   4]
 [  5   6 300   7   8   9]]


---
- np.delete(arr,index,axis)

In [18]:
import numpy as np

matrix = np.array([
 [ 63,   0, 100,   7, -75,  61],
 [  0,   1, 200,   2,   3,   4],
 [  5,   6, 300,   7,   8,   9]
 ])
print(matrix)

matrix = np.delete(matrix, 2, axis=1)
print("After deleting column number 3 :\n",matrix)


[[ 63   0 100   7 -75  61]
 [  0   1 200   2   3   4]
 [  5   6 300   7   8   9]]
After deleting column number 3 :
 [[ 63   0   7 -75  61]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]
