# Aggregate functions

---
- np.sum(arr,axis)

In [1]:
import numpy as np

matrix = np.array([
 [ 63,   0, 100,   7, -75,  61],
 [  0,   1, 200,   2,   3,   4],
 [  5,   6, 300,   7,   8,   9]
 ])

print(matrix,end="\n\n")

#sum
totalSum = np.sum(matrix)
print("Total sum : ",totalSum)
print("Row-wise sum : ",np.sum(matrix,axis=1))
print("Column-wise sum : ",np.sum(matrix,axis=0))


[[ 63   0 100   7 -75  61]
 [  0   1 200   2   3   4]
 [  5   6 300   7   8   9]]

Total sum :  701
Row-wise sum :  [156 210 335]
Column-wise sum :  [ 68   7 600  16 -64  74]


---
- np.mean(arr,axis)

In [2]:
import numpy as np

matrix = np.array([
 [ 63,   0, 100,   7, -75,  61],
 [  0,   1, 200,   2,   3,   4],
 [  5,   6, 300,   7,   8,   9]
 ])

print(matrix,end="\n\n")

#mean
totalmean = np.mean(matrix).round(2)
print("Total mean : ",totalmean)
print("Row-wise mean : ",np.mean(matrix,axis=1).round(2))
print("Column-wise mean : ",np.mean(matrix,axis=0).round(2))


[[ 63   0 100   7 -75  61]
 [  0   1 200   2   3   4]
 [  5   6 300   7   8   9]]

Total mean :  38.94
Row-wise mean :  [26.   35.   55.83]
Column-wise mean :  [ 22.67   2.33 200.     5.33 -21.33  24.67]


---
- np.median(arr,axis)

In [3]:
import numpy as np

matrix = np.array([
 [ 63,   0, 100,   7, -75,  61],
 [  0,   1, 200,   2,   3,   4],
 [  5,   6, 300,   7,   8,   9]
 ])

print(matrix,end="\n\n")

#median
totalmedian = np.median(matrix).round(2)
print("Total median : ",totalmedian)
print("Row-wise median : ",np.median(matrix,axis=1).round(2))
print("Column-wise median : ",np.median(matrix,axis=0).round(2))

[[ 63   0 100   7 -75  61]
 [  0   1 200   2   3   4]
 [  5   6 300   7   8   9]]

Total median :  6.5
Row-wise median :  [34.   2.5  7.5]
Column-wise median :  [  5.   1. 200.   7.   3.   9.]


---
- np.min(arr,axis)
- np.max(arr,axis)

In [4]:
import numpy as np

matrix = np.array([
 [ 63,   0, 100,   7, -75,  61],
 [  0,   1, 200,   2,   3,   4],
 [  5,   6, 300,   7,   8,   9]
 ])

print(matrix,end="\n\n")

#max
totalmax = np.max(matrix).round(2)
print("Total max : ",totalmax)
print("Row-wise max : ",np.max(matrix,axis=1).round(2))
print("Column-wise max : ",np.max(matrix,axis=0).round(2),end="\n\n")

#min
totalmin = np.min(matrix).round(2)
print("Total min : ",totalmin)
print("Row-wise min : ",np.min(matrix,axis=1).round(2))
print("Column-wise min : ",np.min(matrix,axis=0).round(2))

[[ 63   0 100   7 -75  61]
 [  0   1 200   2   3   4]
 [  5   6 300   7   8   9]]

Total max :  300
Row-wise max :  [100 200 300]
Column-wise max :  [ 63   6 300   7   8  61]

Total min :  -75
Row-wise min :  [-75   0   5]
Column-wise min :  [  0   0 100   2 -75   4]
