# Array creation methods

---
- np.arrary(list)

In [7]:
import numpy as np

arr1 = np.array([1,2,3,4])  # vector
arr2 = np.array([   # matrix
    [10,3,-9],
    [-4,34,0]
])
arr3 = np.array([   # tensor
    [[-90,66],[37,48]],
    [[17,34],[75,-88]]
])

print("Vector :\n",arr1)
print("Matrix :\n",arr2)
print("Tensor :\n",arr3)

Vector :
 [1 2 3 4]
Matrix :
 [[10  3 -9]
 [-4 34  0]]
Tensor :
 [[[-90  66]
  [ 37  48]]

 [[ 17  34]
  [ 75 -88]]]


---
- np.zeros((row,col))
- np.ones((row,col))
- np.full((row,col))

In [8]:
import numpy as np

zeros = np.zeros((3,4))
ones = np.ones((2,3))
full = np.full((2,5),12)

print(zeros, ones, full, sep="\n\n")

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[12 12 12 12 12]
 [12 12 12 12 12]]


---
- np.eye(row)

In [9]:
import numpy as np

identity = np.eye(5)

print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---
- np.random.random((row,col))

In [10]:
import numpy as np

random = np.random.random((2,3))

print(random)

[[0.57037915 0.53035372 0.74515042]
 [0.32126296 0.44846821 0.30329824]]


---
- np.arange(start,end,step)
- np.linspace(start,end,count)

In [11]:
import numpy as np

arr = np.arange(0,20,2)
count = np.linspace(10,20,20).round(2)

print(arr,count,sep="\n\n")

[ 0  2  4  6  8 10 12 14 16 18]

[10.   10.53 11.05 11.58 12.11 12.63 13.16 13.68 14.21 14.74 15.26 15.79
 16.32 16.84 17.37 17.89 18.42 18.95 19.47 20.  ]


---
## Cheatsheet

- np.array(list)
- np.zeros((row,col))
- np.ones((row,col))
- np.full((row,col),value)
- np.eye(row)
- np.random.random((row,col))
- np.arange(start,end,step)
- np.linspace(start,end,count)