# Fancy indexing

---

- np.where(condition)

In [6]:
import numpy as np

arr = np.arange(12).reshape((3,4))
print(arr,end="\n\n")

# now select 1, 5, 10 and 7 from the list at once
# positions : 1->(0,1), 5->(1,1), 10->(2,2), 7->(1,3)
print("Values are : ",arr[[0, 1, 2, 1],[1, 1, 2, 3]],end="\n\n")

# we can use np.where(condition) method to use some condition
booleanValues = np.where(arr&1)
print("Boolean values : ",booleanValues)

print("Filtered array : ",arr[booleanValues])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Values are :  [ 1  5 10  7]

Boolean values :  (array([0, 0, 1, 1, 2, 2]), array([1, 3, 1, 3, 1, 3]))
Filtered array :  [ 1  3  5  7  9 11]
