# Linear algebra

---
- np.dot(a,b) or a.dot(b)
- np.matmul(a,b) or a@b
- np.cross(a,b)

In [8]:
import numpy as np

matrix = np.arange(1,13).reshape((3,4))
matrixT = matrix.T.copy()

print("First matrix :\n",matrix)
print("Second matrix :\n",matrixT,end="\n\n")

print("Dot product :\n",matrix.dot(matrixT))
print("Matrix multiplication :\n",matrix@matrixT)
print("Cross product :\n",np.cross(np.array([1,2,3]),np.array([2,3,5])))

First matrix :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second matrix :
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Dot product :
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Matrix multiplication :
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Cross product :
 [ 1  1 -1]


---
- np.lialg.inv(arr)
- np.linalg.det(arr)
- np.linalg.norm(arr)

In [23]:
import numpy as np

matrix = (np.random.random((3,3))*10).round()
print(matrix,end="\n\n")

print("Inverse matrix :\n",np.linalg.inv(matrix).round(2))
print("Determenent : ",np.linalg.det(matrix).round(2))
print("Normalization : ",np.linalg.norm(matrix).round(2))

[[10. 10.  7.]
 [ 1.  5. 10.]
 [ 2.  8.  5.]]

Inverse matrix :
 [[ 0.13 -0.01 -0.16]
 [-0.04 -0.09  0.22]
 [ 0.    0.14 -0.1 ]]
Determenent :  -414.0
Normalization :  21.63
