# Array properties

---
- arr.shape
- arr.size
- arr.ndim
- arr.dtype
- arr.T

In [10]:
import numpy as np

arr = np.arange(20,dtype=np.int64).reshape((4,5))
arrTranspose = arr.T.copy() # .copy() is used to create a copy, otherwise arr.T returns view of the arr, not a copy.

print(arr,end="\n\n")

print("Array shpae : ",arr.shape)
print("Array size : ",arr.size)
print("Array dimension : ",arr.ndim)
print("Array's data type : ",arr.dtype)

print("\nTranspose of arr : \n",arrTranspose,end="\n\n")
print("Transposed array's shpae : ",arrTranspose.shape)
print("Transposed array's size : ",arrTranspose.size)
print("Transposed array's dimension : ",arrTranspose.ndim)
print("Transposed array's data type : ",arrTranspose.dtype)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Array shpae :  (4, 5)
Array size :  20
Array dimension :  2
Array's data type :  int64

Transpose of arr : 
 [[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]

Transposed array's shpae :  (5, 4)
Transposed array's size :  20
Transposed array's dimension :  2
Transposed array's data type :  int64
