# Array reshaping and changing structure

---
- arr.reshape((row,col,...))

In [26]:
import numpy as np

vector = np.arange(24)
print(vector,end="\n\n")

matrix = vector.reshape((4,6))  # retuns as a view
print(matrix,end="\n\n")

tensor = matrix.reshape((2,2,2,3))
print(tensor)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]


---
- arr.flatten()
- arr.ravel()

In [27]:
import numpy as np

arr = np.arange(20).reshape((4,5))

flatten = arr.flatten() # returns copy
print(flatten,end="\n\n")

raveled = arr.ravel() # retuns view
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


---
- arr.swapaxes(0,1)

In [28]:
import numpy as np

tensor = np.arange(24).reshape((3,2,4))
print(tensor,end="\n\n")

swappedTenser = tensor.swapaxes(1,2) # returns view
print(swappedTenser)


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]

 [[16 20]
  [17 21]
  [18 22]
  [19 23]]]
