# Set operations

---
- np.union1d(a,b)
- np.intersection1d(a,b)
- np.setdiff1d(a,b)

In [5]:
import numpy as np

a,b = (np.random.random((3,4))*10).round(),(np.random.random((3,4))*10).round()
print("First matrix :\n",a)
print("Second matrix :\n",b,end="\n\n")

print("Union : ",np.union1d(a,b))
print("Intersection : ",np.intersect1d(a,b))
print("Set difference : ",np.setdiff1d(a,b))

First matrix :
 [[3. 9. 3. 6.]
 [8. 2. 0. 8.]
 [7. 5. 4. 9.]]
Second matrix :
 [[7. 5. 8. 9.]
 [5. 9. 3. 1.]
 [4. 4. 1. 4.]]

Union :  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Intersection :  [3. 4. 5. 7. 8. 9.]
Set difference :  [0. 2. 6.]
