# Indexing and slicing

---

In [18]:
import numpy as np

vector = np.linspace(0,20,12).round(2)
print(vector,end="\n\n")

print("Value at index 1 : ",vector[1])
#slicing retuns view
print("Sliced : ",vector[2:9:2])

[ 0.    1.82  3.64  5.45  7.27  9.09 10.91 12.73 14.55 16.36 18.18 20.  ]

Value at index 1 :  1.82
Sliced :  [ 3.64  7.27 10.91 14.55]


In [ ]:
import numpy as np

matrix = np.arange(20).reshape((4,5))
print(matrix,end="\n\n")

print("Value at position (2,3) : ",matrix[2, 3])
print("Another way : ",matrix[2][3],end="\n\n")

print("Target row number 2 : ",matrix[1])
print("Targe column number 4 :",matrix[:,3],end="\n\n")

print("Target row number 2 with 2 step count : ",matrix[1,::2])
print("Targe column number 4 with 2 step count :",matrix[::2,3],end="\n\n")

# print("Submatrix using slicing :\n",matrix[1:2,])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Value at position (2,3) :  13
Another way :  13

Target row number 2 :  [5 6 7 8 9]
Targe column number 4 : [ 3  8 13 18]

Target row number 2 with 2 step count :  [5 7 9]
Targe column number 4 with 2 step count : [ 3 13]



## Boolean indexing and filtering

---

In [37]:
import numpy as np

arr = np.arange(15).reshape((3,5))
print(arr,end="\n\n")

booleanvalues = arr > 9
print("Boolean Values for arr :\n",booleanvalues)

print("Filtered Value :\n",arr[booleanvalues])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Boolean Values for arr :
 [[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]]
Filtered Value :
 [10 11 12 13 14]
