# Sorting

---
- arr.sort()
- np.sort(arr,axis)

In [8]:
import numpy as np

vector = (np.random.random(10)*10).round()
print(vector)

vector.sort()
print("Sorted vector : ",vector,end="\n\n")

matrix = (np.random.random((3,5))*10).round()
print(matrix)

print("Row-wise sorted :\n",np.sort(matrix))
print("Column-wise sort :\n",np.sort(matrix,axis=0))


[8. 6. 2. 9. 5. 3. 8. 3. 6. 2.]
Sorted vector :  [2. 2. 3. 3. 5. 6. 6. 8. 8. 9.]

[[ 1.  9.  5.  4.  3.]
 [ 6. 10.  7.  3.  6.]
 [ 0.  7.  4.  4.  6.]]
Row-wise sorted :
 [[ 1.  3.  4.  5.  9.]
 [ 3.  6.  6.  7. 10.]
 [ 0.  4.  4.  6.  7.]]
Column-wise sort :
 [[ 0.  7.  4.  3.  3.]
 [ 1.  9.  5.  4.  6.]
 [ 6. 10.  7.  4.  6.]]
