# Vectorized operations of Element wise O/P

---

- a+b
- a-b
- a*b
- a/b
- a**n

In [16]:
import numpy as np

a = np.arange(9).reshape((3,3))
b = np.arange(10,19).reshape((3,3))

print("First matrix :\n",a)
print("Second matrix :\n",b,end="\n\n")

print("First+Second : ",a+b)
print("First-Second : ",a-b)
print("First*Second : ",a*b)
print("First/Second : ",(a/b).round(2))
print("First^2",a**2)


First matrix :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Second matrix :
 [[10 11 12]
 [13 14 15]
 [16 17 18]]

First+Second :  [[10 12 14]
 [16 18 20]
 [22 24 26]]
First-Second :  [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
First*Second :  [[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]
First/Second :  [[0.   0.09 0.17]
 [0.23 0.29 0.33]
 [0.38 0.41 0.44]]
First^2 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


---
- np.sqrt(arr)
- np.exp(arr)
- np.log(arr)
- np.abs(arr)
- np.clip(arr,min,max)
- np.round(arr)

In [30]:
import numpy as np

matrix = np.array([
 [ 63.3,   99.9, 100.19],
 [  2.48,   11.6, 200.77]
 ])

print(matrix,end="\n\n")

print("Square root :\n",np.sqrt(matrix).round(2))
print("Exponential :\n",np.exp(matrix).round(2))
print("Logarithm :\n",np.log(matrix).round(2))
print("Absolue :\n",np.abs(matrix).round(2))
print("Clip :\n",np.clip(matrix,10,20).round(2))
print("Round :\n",np.round(matrix))


[[ 63.3   99.9  100.19]
 [  2.48  11.6  200.77]]

Square root :
 [[ 7.96  9.99 10.01]
 [ 1.57  3.41 14.17]]
Exponential :
 [[3.09628340e+27 2.43230897e+43 3.25060457e+43]
 [1.19400000e+01 1.09097800e+05 1.56064143e+87]]
Logarithm :
 [[4.15 4.6  4.61]
 [0.91 2.45 5.3 ]]
Absolue :
 [[ 63.3   99.9  100.19]
 [  2.48  11.6  200.77]]
Clip :
 [[20.  20.  20. ]
 [10.  11.6 20. ]]
Round :
 [[ 63. 100. 100.]
 [  2.  12. 201.]]
